<?php
		$jokes = array(
            array('setup' => "I'm afraid for the calendar.", 'punchline' => "Its days are numbered."),
            array('setup' => "Why don't eggs tell jokes?", 'punchline' => "They'd crack each other up."),
            array('setup' => "I don't trust stairs.", 'punchline' => "They're always up to something."),
            array('setup' => "What do you call a fake noodle?", 'punchline' => "An impasta."),
            array('setup' => "Why did the scarecrow win an award?", 'punchline' => "Because he was outstanding in his field."),
            array('setup' => "Why don't scientists trust atoms?", 'punchline' => "Because they make up everything."),
            array('setup' => "Why did the bicycle stand up by itself?", 'punchline' => "It was two-tired."),
            array('setup' => "Did you hear about the claustrophobic astronaut?", 'punchline' => "He just needed a little space."),
            array('setup' => "Why don't skeletons fight each other?", 'punchline' => "They don't have the guts."),
            array('setup' => "What do you call cheese that isn't yours?", 'punchline' => "Nacho cheese."),
            array('setup' => "Why couldn't the bicycle stand up by itself?", 'punchline' => "It was two-tired."),
            array('setup' => "What do you call a dog that can do magic?", 'punchline' => "A labracadabrador."),
            array('setup' => "Why was the math book sad?", 'punchline' => "Because it had too many problems."),
            array('setup' => "What do you call an alligator in a vest?", 'punchline' => "An investigator."),
            array('setup' => "What's orange and sounds like a parrot?", 'punchline' => "A carrot."),
            array('setup' => "How does a penguin build its house?", 'punchline' => "Igloos it together."),
            array('setup' => "Why did the golfer bring two pairs of pants?", 'punchline' => "In case he got a hole in one."),
            array('setup' => "What do you call a factory that makes okay products?", 'punchline' => "A satisfactory."),
            array('setup' => "What did the janitor say when he jumped out of the closet?", 'punchline' => "Supplies!"),
            array('setup' => "What do you call a belt made out of watches?", 'punchline' => "A waist of time."),
            array('setup' => "Why couldn't the leopard play hide and seek?", 'punchline' => "Because he was always spotted."),
            array('setup' => "What do you call a man with a rubber toe?", 'punchline' => "Roberto."),
            array('setup' => "What's brown and sticky?", 'punchline' => "A stick."),
            array('setup' => "Why did the old man fall in the well?", 'punchline' => "Because he couldn't see that well."),
            array('setup' => "What do you call a snowman with a six-pack?", 'punchline' => "An abdominal snowman."),
            array('setup' => "How do you organize a space party?", 'punchline' => "You planet."),
            array('setup' => "What do you call a fish wearing a crown?", 'punchline' => "A king fish."),
            array('setup' => "What do you call a bear with no teeth?", 'punchline' => "A gummy bear."),
            array('setup' => "Why do chicken coops have two doors?", 'punchline' => "Because if they had four, they would be chicken sedans."),
            array('setup' => "What do you get when you cross a snowman and a vampire?", 'punchline' => "Frostbite."),
            array('setup' => "What lies at the bottom of the ocean and twitches?", 'punchline' => "A nervous wreck."),
            array('setup' => "Why don't oysters donate to charity?", 'punchline' => "Because they are shellfish."),
            array('setup' => "What do you call a man with no arms and no legs lying in front of your door?", 'punchline' => "Matt."),
            array('setup' => "Why did the tomato turn red?", 'punchline' => "Because it saw the salad dressing."),
            array('setup' => "What do you call a sleepwalking nun?", 'punchline' => "A roamin' Catholic."),
            array('setup' => "What do you get from a pampered cow?", 'punchline' => "Spoiled milk."),
            array('setup' => "Why don't ants get sick?", 'punchline' => "Because they have little ant-bodies."),
            array('setup' => "What do you call a group of unorganized cats?", 'punchline' => "A cat-astrophe."),
            array('setup' => "What do you call a fake noodle?", 'punchline' => "An impasta."),
            array('setup' => "Why can't a nose be 12 inches long?", 'punchline' => "Because then it would be a foot."),
            array('setup' => "What do you call a boomerang that doesn't come back?", 'punchline' => "A stick."),
            array('setup' => "Why did the scarecrow win an award?", 'punchline' => "Because he was outstanding in his field."),
            array('setup' => "What do you call an elephant that doesn't matter?", 'punchline' => "An irrelephant."),
            array('setup' => "Why don't skeletons fight each other?", 'punchline' => "They don't have the guts."),
            array('setup' => "What do you call a fish with no eye?", 'punchline' => "Fsh."),
            array('setup' => "What's the best thing about Switzerland?", 'punchline' => "I don't know, but the flag is a big plus."),
            array('setup' => "What do you call someone with no body and no nose?", 'punchline' => "Nobody knows."),
            array('setup' => "Why did the bicycle fall over?", 'punchline' => "It was two-tired."),
            array('setup' => "Why don't eggs tell jokes?", 'punchline' => "They'd crack each other up."),
            array('setup' => "I don't trust stairs.", 'punchline' => "They're always up to something."),
            array('setup' => "What do you call a fake noodle?", 'punchline' => "An impasta."),
            array('setup' => "Why did the scarecrow win an award?", 'punchline' => "Because he was outstanding in his field."),
            array('setup' => "Why don't scientists trust atoms?", 'punchline' => "Because they make up everything."),
            array('setup' => "Why did the bicycle stand up by itself?", 'punchline' => "It was two-tired."),
            array('setup' => "Did you hear about the claustrophobic astronaut?", 'punchline' => "He just needed a little space."),
            array('setup' => "Why don't skeletons fight each other?", 'punchline' => "They don't have the guts."),
            array('setup' => "What do you call cheese that isn't yours?", 'punchline' => "Nacho cheese."),
            array('setup' => "Why couldn't the bicycle stand up by itself?", 'punchline' => "It was two-tired."),
            array('setup' => "What do you call a dog that can do magic?", 'punchline' => "A labracadabrador."),
            array('setup' => "Why was the math book sad?", 'punchline' => "Because it had too many problems."),
            array('setup' => "What do you call an alligator in a vest?", 'punchline' => "An investigator."),
            array('setup' => "What's orange and sounds like a parrot?", 'punchline' => "A carrot."),
            array('setup' => "How does a penguin build its house?", 'punchline' => "Igloos it together."),
            array('setup' => "Why did the golfer bring two pairs of pants?", 'punchline' => "In case he got a hole in one."),
            array('setup' => "What do you call a factory that makes okay products?", 'punchline' => "A satisfactory."),
            array('setup' => "What did the janitor say when he jumped out of the closet?", 'punchline' => "Supplies!"),
            array('setup' => "What do you call a belt made out of watches?", 'punchline' => "A waist of time."),
            array('setup' => "Why couldn't the leopard play hide and seek?", 'punchline' => "Because he was always spotted."),
        );